---
# role: jomrr.virtinstall
# file: meta/requirements.yml

collections:
  - name: community.libvirt
  - name: git+https://github.com/jam82/ansible-collection-general
    version: main

roles:
  - name: git+https://github.com/jam82/ansible-role-libvirtd
    version: main
